import DocsLayout from '../docs-layout';
import Description from '../docs-components/text-style/description';
import Heading from '../docs-components/text-style/heading';

const CreatingUser = () => {
  return (
    <DocsLayout>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 px-4 md:px-8 py-12">
        <div className="lg:col-span-8 space-y-10">
          <Heading>👤 Creating a User</Heading>
          <Description>
            Only the <strong>Director</strong> role has permission to create new
            users in the system. A user can be a student, professor,
            administrator, or any staff member. The process ensures that all
            user information is correctly stored and secured. On page all users
            just click create user button and fill the form.
          </Description>

          <section className="space-y-4" id="required-fields">
            <h2 className="text-xl font-semibold">📝 Required Fields</h2>
            <div className="grid gap-4">
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>First Name:</strong> The user's given name.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Last Name:</strong> The user's family name.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Profile Picture:</strong> An image to visually identify
                the user.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Unique Government Number:</strong> Used for user
                identification (e.g., JMBG).
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Password:</strong> Automatically generated by the
                system. The Director is responsible for passing it securely to
                the user.
              </div>
            </div>
          </section>
          <section className="space-y-4" id="first-login">
            <h2 className="text-xl font-semibold">
              🔐 First Login & Password Policy
            </h2>
            <div className="grid gap-4">
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Initial Login:</strong> The user logs in using the
                auto-generated password provided by the Director.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Password Reset (First Time):</strong> On first login,
                the user is required to reset their password and set their own.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>One-Time Reset:</strong> This password reset can only
                happen once, during the first login.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Future Changes:</strong> Any future password changes
                require Director approval.
              </div>
            </div>
          </section>

          <section className="space-y-4" id="update-user">
            <h2 className="text-xl font-semibold">✏️ Updating Users</h2>
            <div className="grid gap-4">
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Director Access:</strong> The Director can update any
                user’s information, including name, role, picture, or assigned
                classes.
              </div>
              <div className="border border-muted rounded-lg p-4 bg-muted/40">
                <strong>Password Reset (Manual):</strong> If necessary, the
                Director can reset a user's password manually by going to the
                user profile and click button set initial password.
              </div>
            </div>
          </section>

          <p className="mt-8 text-base leading-relaxed">
            Creating users is a sensitive action and must be handled with care.
            Only trusted Directors should perform this task, and password
            sharing should be done securely and responsibly.
          </p>
        </div>

        <aside className="lg:col-span-4 hidden lg:block">
          <div className="sticky top-24 bg-muted border p-4 rounded-lg space-y-2">
            <h3 className="text-lg font-semibold mb-2">On this page</h3>
            <ul className="space-y-1 text-sm">
              <li>
                <a
                  href="#required-fields"
                  className="hover:underline text-muted-foreground"
                >
                  📝 Required Fields
                </a>
              </li>
              <li>
                <a
                  href="#first-login"
                  className="hover:underline text-muted-foreground"
                >
                  🔐 First Login
                </a>
              </li>
              <li>
                <a
                  href="#update-user"
                  className="hover:underline text-muted-foreground"
                >
                  ✏️ Updating Users
                </a>
              </li>
            </ul>
          </div>
        </aside>
      </div>
    </DocsLayout>
  );
};

export default CreatingUser;
